services:
    dotcruz-postgres:
        image: postgres:latest
        container_name: dotcruz-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_AUTH_USER}
            POSTGRES_PASSWORD: ${DB_AUTH_PASS}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    dotcruz-mongo:
        image: mongo:latest
        container_name: dotcruz-mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_NOTIF_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_NOTIF_PASS}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

    rabbitmq:
        image: rabbitmq:3-management
        container_name: dotcruz-rabbitmq
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=${RMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    postgres_data:
    mongodb_data:
    rabbitmq_data:
