services:
    dotcruz-postgres:
        image: postgres:18 # Versão major fixada
        container_name: dotcruz-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_AUTH_NAME}
            POSTGRES_USER: ${DB_AUTH_USER}
            POSTGRES_PASSWORD: ${DB_AUTH_PASS}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${DB_AUTH_USER} -d ${DB_AUTH_NAME}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    dotcruz-mongo:
        image: mongo:8 # Versão major fixada
        container_name: dotcruz-mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MG_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MG_DB_PASS}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: dotcruz-rabbitmq
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=${RMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
    mongodb_data:
    rabbitmq_data:
